AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Repository for Docker Images

Parameters:
  ProjectName:
    Type: String

Resources:
  LambdaTestingRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub '${ProjectName}-lambda-tester-repo'
  ResourcesBucket:
    Type: AWS::S3::Bucket

Outputs:
  RepoName:
    Value: !Ref LambdaTestingRepository
    Description: Name of the ECR repo
  RepoUri:
    Value: !GetAtt LambdaTestingRepository.RepositoryUri
    Description: URI of the ECR repo
  BucketName:
    Value: !Ref ResourcesBucket
    Description: Name of the resources bucket
